do not call panic func when nothing was initialized yet

diff --git a/justclash/files/usr/bin/justclash b/justclash/files/usr/bin/justclash
--- a/justclash/files/usr/bin/justclash
+++ b/justclash/files/usr/bin/justclash
@@ -244,7 +244,8 @@ core_validate_yaml() {
     if [ "$grep_test_exit_code" -eq 0 ] || [ "$app_exit_code" -ne 0 ] || [ "$grep_error_exit_code" -eq 0 ]; then
         log 0 "Yaml configuration incorrect!" "❌"
         log 0 "$test_output" "❌"
-        panic "Mihomo config validation is failed." "❌"
+        log 0 "Mihomo config validation is failed." "❌"
+        return 1
     fi
     return 0
 }
@@ -277,6 +278,9 @@ start() {
 
     log 2 "Validating yaml configuration..." "📦"
     core_validate_yaml
+    if [ $? = 1 ]; then
+        return 1
+    fi
 
     log 2 "Configuring TPROXY routing and creating NFTables table" "🔑"
     nft_table_add
