fix and rework start logic, friendlywrt support, nft tables rework

diff --git a/justclash/files/usr/bin/justclash b/justclash/files/usr/bin/justclash
--- a/justclash/files/usr/bin/justclash
+++ b/justclash/files/usr/bin/justclash
@@ -16,9 +16,6 @@
 
 # Variable for standalone or procd start
 PROCD_MODE=0
-# service pidfile path
-PIDFILE="/var/run/justclash.pid"
-
 
 # setup procd variable: $JUSTCLASH_ENV passed from init.d start
 [ "$JUSTCLASH_ENV" = "procd" ] && PROCD_MODE=1 || PROCD_MODE=0
@@ -38,11 +35,10 @@ CORE_PATH_INFOBIN="/usr/bin/justclash_info"
 INITD_PATH="/etc/init.d/justclash"
 # workdir path (in RAM)
 CORE_WORKDIR_PATH="/tmp/justclash/"
-# fifo pipe for background process redirection to justclash syslogs
-FIFOPATH="/tmp/justclash/justclash.fifo"
 OUTPUT_YAML_CONFIG_PATH="${CORE_WORKDIR_PATH}config.yaml"
 OVERRIDE_YAML_CONFIG_PATH="/var/override.${CORE_BIN_NAME}.yaml"
 DEFAULT_CONFIG_PATH="/var/default.justclash.config"
+CORE_RESTART_MAX_RETRIES=3
 
 NFT_TABLE_NAME="justclash_tproxy"
 NFT_FWMARK_FINAL=1
@@ -61,9 +57,8 @@ NTP_IPS="194.190.168.1 195.208.185.17 193.232.128.6 216.239.35.0"
 #ALLOWED_INTERFACES='{ lan*, br-lan }'
 # List of conflicting packages:
 # podkop (custom proxy)
-# iptables-mod-extra (additional iptables modules)
 # and https-dns-proxy (DNS over HTTPS proxy)
-CONFLICTED_PACKAGES="podkop iptables-mod-extra https-dns-proxy"
+CONFLICTED_PACKAGES="podkop https-dns-proxy"
 CONFLICTED_PATTERNS_DHCP_CONFIG="doh_backup_noresolv doh_backup_server doh_server"
 CONFLICTED_PATTERNS_FILEPATH="/etc/config/dhcp"
 RESOLVCONF_FILEPATH="/etc/resolv.conf"
@@ -217,13 +212,25 @@ ntp_force_sync() {
     sleep 2
 }
 
+
+compat_fixes() {
+    if ! command -v lsmod >/dev/null 2>&1; then
+        log 1 "lsmod is missing. Can't check for kernel modules" "⚠️"
+    else
+        if lsmod | grep -q br_netfilter && [ "$(sysctl -n net.bridge.bridge-nf-call-iptables 2>/dev/null)" = "1" ]; then
+            log 1 "br_netfilter is enabled. FriendlyWRT? Fixing module params..." "⚠️"
+            sysctl -w net.bridge.bridge-nf-call-iptables=0
+            sysctl -w net.bridge.bridge-nf-call-ip6tables=0
+            log 1 "Set net.bridge.bridge-nf-call-iptables=0" "⚠️"
+            log 1 "Set net.bridge.bridge-nf-call-ip6tables=0" "⚠️"
+        else
+            log 2 "No compatibility fixes required."
+        fi
+    fi
+}
+
 start() {
     log 2 "Initializing Justclash service..." "⏳"
-
-    if [ -f "$PIDFILE" ]; then
-        log 1 "Detected PID file for service... Stopping instance" "⚠️"
-        stop_core
-    fi
 
     if [ ! -f "$CORE_PATH" ]; then
         log 1 "Mihomo core is not installed." "⚠️"
@@ -235,6 +242,9 @@ start() {
 
     log 2 "Checking for non critical conflicts" "🐞"
     check_for_conflicts_warn
+
+    log 2 "Fixing known compatibility problems" "🔑"
+    compat_fixes
 
     log 2 "Synchronizing system time" "🕒"
     ntp_force_sync
@@ -274,102 +284,53 @@ restart() {
 
 # WARNING: TRY TO NOT USE FUNC MANUALLY - MUST CLEAR ROUTES AND DNSMASQ
 start_core() {
-    clear_fifo
-    if [ "$PROCD_MODE" -eq 0 ]; then
-        log 1 "Running mihomo in foreground (manual mode)" "⚠️"
-        "$CORE_PATH" -d "$CORE_WORKDIR_PATH" &
-        echo $! > "$PIDFILE"
-        wait $!
-        rm -f "$PIDFILE" # Удаляем PID-файл после завершения
+    local attempt=0
+    log 2 "Start: configured retries: $CORE_RESTART_MAX_RETRIES" "🐱"
+
+    if [ "$PROCD_MODE" -eq 1 ]; then
+        local attempt=0
+
+        while [ "$attempt" -lt "$CORE_RESTART_MAX_RETRIES" ]; do
+            "$CORE_PATH" -d "$CORE_WORKDIR_PATH" 2>&1 | sed 's/time="[^"]*"/mihomo/' | logger -t justclash
+            exit_code=$?
+            log 1 "Restart: mihomo exited with code $exit_code" "💀"
+
+            if [ "$exit_code" -eq 0 ]; then
+                break
+            fi
+
+            attempt=$((attempt + 1))
+            log 1 "Restart:  mihomo crashed, attempt $attempt of $CORE_RESTART_MAX_RETRIES" "💀"
+
+            if [ "$attempt" -ge "$CORE_RESTART_MAX_RETRIES" ]; then
+                log 1 "Restart:  Failed to restart mihomo after $CORE_RESTART_MAX_RETRIES attempts, exiting" "💀"
+                exit "$exit_code"
+            fi
+
+            sleep 5
+        done
     else
-        log 2 "Running mihomo in background (procd mode)" "🐱"
-        mkfifo "$FIFOPATH"
-        "$CORE_PATH" -d "$CORE_WORKDIR_PATH" > "$FIFOPATH" &
-        echo $! > "$PIDFILE"
-        sed 's/time="[^"]*"/mihomo/' < "$FIFOPATH" | logger -t justclash &
+        "$CORE_PATH" -d "$CORE_WORKDIR_PATH" 2>&1
+        exit_code=$?
+        log 1 "Manual start: mihomo exited with code $exit_code" "💀"
+        if [ "$exit_code" -ne 0 ]; then
+            log 1 "Manual start: mihomo crashed, exiting" "💀"
+            exit "$exit_code"
+        fi
     fi
 }
 
 # WARNING: TRY TO NOT USE FUNC MANUALLY - MUST CLEAR ROUTES AND DNSMASQ
 stop_core() {
-    local pid
-
-    if [ -f "$PIDFILE" ]; then
-        pid=$(cat "$PIDFILE")
-        log 2 "Stopping core process (PID $pid)" "🐱"
-
-        kill -TERM "$pid" 2>/dev/null
-
-        local count=0
-        while kill -0 "$pid" 2>/dev/null && [ $count -lt 4 ]; do
-            sleep 1
-            count=$((count+1))
-        done
-
-        if kill -0 "$pid" 2>/dev/null; then
-            log 1 "Force killing process $pid" "🐱"
-            kill -9 "$pid"
+    if pgrep -f "$(basename "$0")" >/dev/null; then
+        pids=$(pgrep -f "$(basename "$CORE_PATH")")
+        if [ -n "$pids" ]; then
+            kill "$pids" 2>/dev/null
         fi
-
-        rm -f "$PIDFILE"
-        log 2 "Core process stopped" "✅"
+        log 2 "Core process stopped" "🐱"
     else
-        log 1 "PID file not found, using fallback stop method"
-        if ! killall "$(basename "$CORE_PATH")" >/dev/null 2>&1; then
-            log 2 "Process not found: $(basename "$CORE_PATH")" "⚠️"
-        fi
+       log 2 "Process not found: $(basename "$CORE_PATH")" "⚠️"
     fi
-
-   clear_fifo
-}
-
-clear_fifo() {
-    if [ -f "$FIFOPATH" ]; then
-        rm -f "$FIFOPATH" 2>/dev/null
-    fi
-}
-
-info_device() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_device)
-    echo "$res"
-}
-
-info_openwrt() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_openwrt)
-    echo "$res"
-}
-
-info_mihomo() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_core)
-    echo "$res"
-}
-
-info_package() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_package)
-    echo "$res"
-}
-
-info_luci() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_luci)
-    echo "$res"
-}
-
-info_conns_console() {
-    local res
-    res=$($CORE_PATH_INFOBIN info_conns_console)
-    echo "$res"
-}
-
-systemlogs() {
-    local res
-    local lines=${1:-40}
-    res=$($CORE_PATH_INFOBIN systemlogs "$lines")
-    echo "$res"
 }
 
 diag_nft() {
@@ -399,7 +360,7 @@ cleanup_fwmark() {
     done
 }
 
-nft_table_add() {
+nft_table_add_old() {
     local tproxy_port proxy_fwmark_hex fake_ip_range
     config_get tproxy_port proxy tproxy_port
     config_get fake_ip_range proxy fake_ip_range
@@ -409,12 +370,14 @@ nft_table_add() {
 
     proxy_fwmark_hex=$(printf "0x%02X" "$NFT_FWMARK_PROXY")
 
-    nft delete table ip "$NFT_TABLE_NAME" 2>/dev/null || true
+    if nft list table ip "$NFT_TABLE_NAME" 2>/dev/null; then
+        nft delete table ip "$NFT_TABLE_NAME"
+    fi
 
     # Создаём таблицу, цепочки и наборы
     nft add table ip "$NFT_TABLE_NAME"
     nft add chain ip "$NFT_TABLE_NAME" prerouting '{ type filter hook prerouting priority mangle; policy accept; }'
-    nft add chain ip "$NFT_TABLE_NAME" output '{ type route hook output priority mangle; policy accept; }'
+    #nft add chain ip "$NFT_TABLE_NAME" output '{ type route hook output priority mangle; policy accept; }'
     nft add set ip "$NFT_TABLE_NAME" fake_ips '{ type ipv4_addr; flags interval; }'
     nft add element ip "$NFT_TABLE_NAME" fake_ips { "$fake_ip_range" }
 
@@ -454,22 +417,93 @@ nft_table_add() {
     nft add rule ip "$NFT_TABLE_NAME" prerouting meta mark "$NFT_FWMARK_FINAL" ip protocol tcp tproxy to 127.0.0.1:"$tproxy_port"
     nft add rule ip "$NFT_TABLE_NAME" prerouting meta mark "$NFT_FWMARK_FINAL" ip protocol udp tproxy to 127.0.0.1:"$tproxy_port"
 
-    nft add rule ip "$NFT_TABLE_NAME" output mark "$proxy_fwmark_hex" return
-    nft add rule ip "$NFT_TABLE_NAME" output meta skuid 0 return
+    #nft add rule ip "$NFT_TABLE_NAME" output mark "$proxy_fwmark_hex" return
+    #nft add rule ip "$NFT_TABLE_NAME" output meta skuid 0 return
 
-    nft add rule ip "$NFT_TABLE_NAME" output ip daddr @fake_ips ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
-    nft add rule ip "$NFT_TABLE_NAME" output ip daddr @fake_ips ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
+    #nft add rule ip "$NFT_TABLE_NAME" output ip daddr @fake_ips ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
+    #nft add rule ip "$NFT_TABLE_NAME" output ip daddr @fake_ips ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
 
-    for intf in wan ppp tun tap wg lxc veth vnet docker dummy; do
-        nft add rule ip "$NFT_TABLE_NAME" output iifname "${intf}*" return
-    done
+    #for intf in wan ppp tun tap wg lxc veth vnet docker dummy; do
+    #    nft add rule ip "$NFT_TABLE_NAME" output iifname "${intf}*" return
+    #done
 
+    #for addr in $exclude_addrs; do
+    #    nft add rule ip "$NFT_TABLE_NAME" output ip daddr "$addr" return
+    #done
+
+    #nft add rule ip "$NFT_TABLE_NAME" output meta mark 0 ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
+    #nft add rule ip "$NFT_TABLE_NAME" output meta mark 0 ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
+
+    cleanup_fwmark
+    if ! ip rule list | grep -q "fwmark 0x1 lookup 100"; then
+        ip rule add fwmark "$NFT_FWMARK_FINAL" table 100
+    fi
+
+    if ! ip route show table 100 | grep -q "local 0.0.0.0/0 dev lo"; then
+        ip route add local 0.0.0.0/0 dev lo table 100
+    fi
+
+    log 1 "TPROXY: port=$tproxy_port, fwmark=1 table=100"
+}
+
+nft_table_add() {
+    local tproxy_port proxy_fwmark_hex fake_ip_range
+    config_get tproxy_port proxy tproxy_port
+    config_get fake_ip_range proxy fake_ip_range
+
+    [ -z "$tproxy_port" ] && panic "tproxy_port not set"
+    [ -z "$fake_ip_range" ] && panic "fake_ip_range not set"
+
+    proxy_fwmark_hex=$(printf "0x%02X" "$NFT_FWMARK_PROXY")
+
+    if nft list table ip "$NFT_TABLE_NAME" 2>/dev/null; then
+        nft delete table ip "$NFT_TABLE_NAME"
+    fi
+
+    # Создаём таблицу, цепочку и набор адресов
+    nft add table ip "$NFT_TABLE_NAME"
+    nft add chain ip "$NFT_TABLE_NAME" prerouting '{ type filter hook prerouting priority mangle; policy accept; }'
+    nft add set ip "$NFT_TABLE_NAME" fake_ips '{ type ipv4_addr; flags interval; }'
+    nft add element ip "$NFT_TABLE_NAME" fake_ips { "$fake_ip_range" }
+
+    local exclude_addrs="
+        0.0.0.0/8
+        10.0.0.0/8
+        100.64.0.0/10
+        127.0.0.0/8
+        169.254.0.0/16
+        172.16.0.0/12
+        192.0.0.0/24
+        192.0.2.0/24
+        192.88.99.0/24
+        192.168.0.0/16
+        198.51.100.0/24
+        203.0.113.0/24
+        224.0.0.0/4
+        240.0.0.0/4
+    "
+
+    # Исключения по адресам для трафика с br-lan
     for addr in $exclude_addrs; do
-        nft add rule ip "$NFT_TABLE_NAME" output ip daddr "$addr" return
+        nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" ip daddr "$addr" return
     done
 
-    nft add rule ip "$NFT_TABLE_NAME" output meta mark 0 ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
-    nft add rule ip "$NFT_TABLE_NAME" output meta mark 0 ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
+    # Исключение по fwmark для br-lan
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" mark "$proxy_fwmark_hex" return
+
+    # Маркируем fake IP для br-lan
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" ip daddr @fake_ips ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" ip daddr @fake_ips ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
+
+    # Маркируем остальной трафик с br-lan
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" ip protocol tcp meta mark set "$NFT_FWMARK_FINAL"
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" ip protocol udp meta mark set "$NFT_FWMARK_FINAL"
+
+    # TPROXY только для трафика с br-lan и нужной меткой
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" meta mark "$NFT_FWMARK_FINAL" ip protocol tcp tproxy to 127.0.0.1:"$tproxy_port"
+    nft add rule ip "$NFT_TABLE_NAME" prerouting iifname "br-lan" meta mark "$NFT_FWMARK_FINAL" ip protocol udp tproxy to 127.0.0.1:"$tproxy_port"
+
+    # output-цепочка не создаётся и не используется!
 
     cleanup_fwmark
     if ! ip rule list | grep -q "fwmark 0x1 lookup 100"; then
@@ -625,6 +659,50 @@ check_for_conflicts_warn() {
         log 1 "If you intend to use a local DNS service, these entries should be removed." "⚠️"
     fi
 }
+
+info_device() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_device)
+    echo "$res"
+}
+
+info_openwrt() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_openwrt)
+    echo "$res"
+}
+
+info_mihomo() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_core)
+    echo "$res"
+}
+
+info_package() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_package)
+    echo "$res"
+}
+
+info_luci() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_luci)
+    echo "$res"
+}
+
+info_conns_console() {
+    local res
+    res=$($CORE_PATH_INFOBIN info_conns_console)
+    echo "$res"
+}
+
+systemlogs() {
+    local res
+    local lines=${1:-40}
+    res=$($CORE_PATH_INFOBIN systemlogs "$lines")
+    echo "$res"
+}
+
 # TODO: Finish dynamic prefix
 generate_yaml_array() {
     local section_type="$1"
@@ -657,7 +735,7 @@ ucibool_to_yaml_bool () {
 }
 
 core_generate_yaml() {
-    local log_level tproxy_port unified_delay routing_mark
+    local log_level tproxy_port unified_delay
     local tcp_concurrent external_controller_port global_client_fingerprint
     local keep_alive_idle keep_alive_interval profile_store_selected profile_store_fake_ip
     local core_ntp_enabled core_ntp_interval core_ntp_server core_ntp_port  core_ntp_write_system
@@ -806,7 +884,6 @@ core_prepare_workdir() {
 
     if [ -d "$CORE_WORKDIR_PATH" ]; then
         [ -f "$OUTPUT_YAML_CONFIG_PATH" ] && rm -f "$OUTPUT_YAML_CONFIG_PATH"
-        [ -f "$FIFOPATH" ] && rm -f "$FIFOPATH"
     else
         mkdir -p "$CORE_WORKDIR_PATH"
     fi
